import type { ProviderWithModels, FlatModel } from './types';

const STATIC_TIMESTAMP = '2026-08-13T10:00:00.000Z';

export const INITIAL_PROVIDERS: ProviderWithModels[] = [
  {
    id: 'prov-groq',
    name: 'Groq',
    slug: 'groq',
    website: 'https://groq.com',
    signup_url: 'https://console.groq.com',
    api_key_guide: '1. Sign up at console.groq.com\n2. Navigate to API Keys section\n3. Click "Create API Key"\n4. Set GROQ_API_KEY env variable',
    logo_url: 'https://groq.com/wp-content/uploads/2024/03/Groq_Logo_Primary_RGB_Red.png',
    description: 'Ultra-fast LPU inference engine powering open-weights models like Llama 3.3, DeepSeek R1, Gemma 2, and Whisper at multi-hundred tokens/sec.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'groq/groq-sdk-python',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-groq-1',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B Versatile',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-2',
        provider_id: 'prov-groq',
        model_api_id: 'deepseek-r1-distill-llama-70b',
        name: 'DeepSeek R1 Distill Llama 70B',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-3',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-4',
        provider_id: 'prov-groq',
        model_api_id: 'gemma2-9b-it',
        name: 'Gemma 2 9B Instruction',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 88,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-5',
        provider_id: 'prov-groq',
        model_api_id: 'mixtral-8x7b-32768',
        name: 'Mixtral 8x7B Instruct',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-6',
        provider_id: 'prov-groq',
        model_api_id: 'llama-guard-3-8b',
        name: 'Llama Guard 3 8B (Safety Filter)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Safety Guardrail',
        popularity_score: 82,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-7',
        provider_id: 'prov-groq',
        model_api_id: 'whisper-large-v3',
        name: 'Whisper Large v3 (Speech-to-Text)',
        context_window: 1500,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-8',
        provider_id: 'prov-groq',
        model_api_id: 'whisper-large-v3-turbo',
        name: 'Whisper Large v3 Turbo',
        context_window: 1500,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-9',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.2-11b-vision-preview',
        name: 'Llama 3.2 11B Vision Preview',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 7000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-10',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.2-90b-vision-preview',
        name: 'Llama 3.2 90B Vision Preview',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 3500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-11',
        provider_id: 'prov-groq',
        model_api_id: 'deepseek-r1-distill-qwen-32b',
        name: 'DeepSeek R1 Distill Qwen 32B',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-12',
        provider_id: 'prov-groq',
        model_api_id: 'qwen-2.5-coder-32b',
        name: 'Qwen 2.5 Coder 32B (Groq LPU)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-openrouter',
    name: 'OpenRouter',
    slug: 'openrouter',
    website: 'https://openrouter.ai',
    signup_url: 'https://openrouter.ai/keys',
    api_key_guide: '1. Register on openrouter.ai\n2. Go to Keys tab and click Create Key\n3. Filter models with :free tag',
    logo_url: 'https://openrouter.ai/favicon.ico',
    description: 'Unified AI gateway hosting over 20+ completely free LLM models alongside paid endpoints with zero minimum commitment.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'alexrudy/openrouter',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-or-1',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemini-2.0-flash-exp:free',
        name: 'Gemini 2.0 Flash Experimental (Free)',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemini-2.0-flash-exp:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 200,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-2',
        provider_id: 'prov-openrouter',
        model_api_id: 'deepseek/deepseek-r1:free',
        name: 'DeepSeek R1 (Free OpenRouter)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/deepseek/deepseek-r1:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-3',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.3-70b-instruct:free',
        name: 'Llama 3.3 70B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.3-70b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-4',
        provider_id: 'prov-openrouter',
        model_api_id: 'qwen/qwen-2.5-72b-instruct:free',
        name: 'Qwen 2.5 72B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/qwen/qwen-2.5-72b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-5',
        provider_id: 'prov-openrouter',
        model_api_id: 'mistralai/mistral-7b-instruct:free',
        name: 'Mistral 7B Instruct v0.3 (Free)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/mistralai/mistral-7b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 89,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-6',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemma-2-9b-it:free',
        name: 'Gemma 2 9B Instruct (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemma-2-9b-it:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 87,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-7',
        provider_id: 'prov-openrouter',
        model_api_id: 'nousresearch/hermes-3-llama-3.1-405b:free',
        name: 'Hermes 3 Llama 3.1 405B (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/nousresearch/hermes-3-llama-3.1-405b:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 200,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-8',
        provider_id: 'prov-openrouter',
        model_api_id: 'sophosympatheia/rogue-rose-103b-v0.2:free',
        name: 'Rogue Rose 103B v0.2 (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/sophosympatheia/rogue-rose-103b-v0.2:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 200,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 80,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-9',
        provider_id: 'prov-openrouter',
        model_api_id: 'huggingfaceh4/zephyr-7b-beta:free',
        name: 'Zephyr 7B Beta (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/huggingfaceh4/zephyr-7b-beta:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 83,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-10',
        provider_id: 'prov-openrouter',
        model_api_id: 'openchat/openchat-7b:free',
        name: 'OpenChat 3.5 7B (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/openchat/openchat-7b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 81,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-11',
        provider_id: 'prov-openrouter',
        model_api_id: 'gryphe/mythomax-l2-13b:free',
        name: 'MythoMax L2 13B (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/gryphe/mythomax-l2-13b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 84,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-12',
        provider_id: 'prov-openrouter',
        model_api_id: 'liquid/lfm-40b:free',
        name: 'Liquid LFM 40B MoE (Free)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/liquid/lfm-40b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 88,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-13',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.2-11b-vision-instruct:free',
        name: 'Llama 3.2 11B Vision Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.2-11b-vision-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-14',
        provider_id: 'prov-openrouter',
        model_api_id: 'nvidia/llama-3.1-nemotron-70b-instruct:free',
        name: 'NVIDIA Llama 3.1 Nemotron 70B (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/nvidia/llama-3.1-nemotron-70b-instruct:free',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-15',
        provider_id: 'prov-openrouter',
        model_api_id: 'qwen/qwen-2.5-coder-32b-instruct:free',
        name: 'Qwen 2.5 Coder 32B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/qwen/qwen-2.5-coder-32b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-16',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.1-8b-instruct:free',
        name: 'Llama 3.1 8B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.1-8b-instruct:free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-17',
        provider_id: 'prov-openrouter',
        model_api_id: 'microsoft/phi-3-medium-128k-instruct:free',
        name: 'Phi-3 Medium 128k Instruct (Free)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/microsoft/phi-3-medium-128k-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 800,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 86,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-18',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemma-2-27b-it:free',
        name: 'Gemma 2 27B Instruct (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemma-2-27b-it:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 89,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-19',
        provider_id: 'prov-openrouter',
        model_api_id: 'deepseek/deepseek-chat:free',
        name: 'DeepSeek V3 Chat (Free)',
        context_window: 64000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/deepseek/deepseek-chat:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-google-aistudio',
    name: 'Google AI Studio',
    slug: 'google-aistudio',
    website: 'https://aistudio.google.com',
    signup_url: 'https://aistudio.google.com/app/apikey',
    api_key_guide: '1. Visit Google AI Studio\n2. Click "Get API key"\n3. Generate key in Google Cloud project\n4. Generous free tier quotas reset daily',
    logo_url: 'https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a611345.svg',
    description: 'Official developer interface for Gemini models featuring 1 million+ token context window, audio/video input, and high speed.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'google-gemini/generative-ai-js',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-goog-37-flash',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.7-flash',
        name: 'Gemini 3.7 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini#gemini-3.7-flash',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-37-thinking',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.7-flash-thinking',
        name: 'Gemini 3.7 Flash Thinking',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Reasoning',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-31-lite',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.1-flash-lite',
        name: 'Gemini 3.1 Flash Lite',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-1',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-2',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-2.0-flash-lite',
        name: 'Gemini 2.0 Flash Lite',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-3',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        context_window: 2097152,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 2,
        rate_limit_per_day: 50,
        multimodal: true,
        category: 'Large Context',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-4',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-gemma2-27b',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemma-2-27b-it',
        name: 'Gemma 2 27B IT',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemma',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cerebras',
    name: 'Cerebras AI',
    slug: 'cerebras',
    website: 'https://cerebras.ai',
    signup_url: 'https://cloud.cerebras.ai',
    api_key_guide: '1. Sign up at cloud.cerebras.ai\n2. Get API key from dashboard\n3. Enjoy lightning-fast 2,000+ tokens/sec output rate.',
    logo_url: 'https://cerebras.ai/wp-content/uploads/2023/11/logo.svg',
    description: 'Wafer-Scale Engine wafer-chip hardware delivering unmatched generation speeds up to 2,000 tokens per second for Llama 3 models.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'cerebras/cerebras-cloud-sdk',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cer-1',
        provider_id: 'prov-cerebras',
        model_api_id: 'llama3.3-70b',
        name: 'Llama 3.3 70B (Wafer Speed)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.cerebras.ai',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Extreme Speed',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-cer-2',
        provider_id: 'prov-cerebras',
        model_api_id: 'llama3.1-8b',
        name: 'Llama 3.1 8B (Wafer Speed)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.cerebras.ai',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Extreme Speed',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-sambanova',
    name: 'SambaNova Systems',
    slug: 'sambanova',
    website: 'https://sambanova.ai',
    signup_url: 'https://cloud.sambanova.ai',
    api_key_guide: '1. Register at cloud.sambanova.ai\n2. Generate API key\n3. Full free access to DeepSeek R1 671B and Llama 3.3 70B.',
    logo_url: 'https://sambanova.ai/hubfs/SambaNova_Logo_Primary_RGB.svg',
    description: 'SN40L Reconfigurable Dataflow Unit architecture serving full-size 671B parameter DeepSeek R1 and Llama 3.3 70B at ultra speed.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'sambanova/sambanova-suite',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-samba-1',
        provider_id: 'prov-sambanova',
        model_api_id: 'DeepSeek-R1',
        name: 'DeepSeek R1 (Full 671B)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.sambanova.ai',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-samba-2',
        provider_id: 'prov-sambanova',
        model_api_id: 'Meta-Llama-3.3-70B-Instruct',
        name: 'Meta Llama 3.3 70B Instruct',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.sambanova.ai',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-huggingface',
    name: 'Hugging Face Inference API',
    slug: 'huggingface',
    website: 'https://huggingface.co',
    signup_url: 'https://huggingface.co/settings/tokens',
    api_key_guide: '1. Sign up on Hugging Face\n2. Navigate to Settings > Access Tokens\n3. Create a read token\n4. Call router.huggingface.co endpoints',
    logo_url: 'https://huggingface.co/front/assets/huggingface_logo-noborder.svg',
    description: 'Serverless inference endpoint hosting thousands of open-source fine-tuned models and community releases for free.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'huggingface/huggingface_hub',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-hf-1',
        provider_id: 'prov-huggingface',
        model_api_id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
        name: 'Qwen 2.5 Coder 32B Instruct',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-hf-2',
        provider_id: 'prov-huggingface',
        model_api_id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
        name: 'DeepSeek R1 Distill Qwen 32B (Serverless)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-github-models',
    name: 'GitHub Models',
    slug: 'github-models',
    website: 'https://github.com/marketplace/models',
    signup_url: 'https://github.com/marketplace/models',
    api_key_guide: '1. Go to github.com/marketplace/models\n2. Log in with your GitHub account\n3. Generate a GitHub Personal Access Token (PAT)\n4. Enjoy free access to OpenAI GPT-4o, Llama 3.3, and Mistral Large!',
    logo_url: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png',
    description: 'GitHub official free AI inference playground giving developers direct OpenAI, Llama 3.3, and Azure AI model access with a standard GitHub Personal Access Token.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'open-free-llm-api/awesome-freellm-apis',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-ghm-1',
        provider_id: 'prov-github-models',
        model_api_id: 'gpt-4o',
        name: 'GPT-4o (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-openai/gpt-4o',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-2',
        provider_id: 'prov-github-models',
        model_api_id: 'gpt-4o-mini',
        name: 'GPT-4o Mini (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-openai/gpt-4o-mini',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-3',
        provider_id: 'prov-github-models',
        model_api_id: 'Meta-Llama-3.3-70B-Instruct',
        name: 'Llama 3.3 70B Instruct (GitHub)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-meta/Meta-Llama-3-3-70B-Instruct',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-4',
        provider_id: 'prov-github-models',
        model_api_id: 'Mistral-large-2411',
        name: 'Mistral Large 2 (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-mistral/Mistral-large-2411',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-nvidia-nim',
    name: 'NVIDIA Build NIMs',
    slug: 'nvidia-nim',
    website: 'https://build.nvidia.com',
    signup_url: 'https://build.nvidia.com',
    api_key_guide: '1. Sign in to build.nvidia.com with NVIDIA account\n2. Receive 1,000 free API credits\n3. Access accelerated NIM endpoints for Llama 3.3 70B & DeepSeek R1',
    logo_url: 'https://www.nvidia.com/favicon.ico',
    description: 'NVIDIA official cloud microservices platform hosting optimized inference containers for DeepSeek R1, Llama 3.3 70B, and Nemotron with free API testing credits.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'MrFadiAi/free-llm-gateway',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-nv-1',
        provider_id: 'prov-nvidia-nim',
        model_api_id: 'deepseek-ai/deepseek-r1',
        name: 'DeepSeek R1 (NVIDIA NIM)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://build.nvidia.com/deepseek-ai/deepseek-r1',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-nv-2',
        provider_id: 'prov-nvidia-nim',
        model_api_id: 'nvidia/llama-3.1-nemotron-70b-instruct',
        name: 'NVIDIA Llama 3.1 Nemotron 70B NIM',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-siliconflow',
    name: 'SiliconFlow (SiliconCloud)',
    slug: 'siliconflow',
    website: 'https://siliconflow.cn',
    signup_url: 'https://cloud.siliconflow.cn',
    api_key_guide: '1. Register at cloud.siliconflow.cn\n2. Navigate to API Keys section\n3. Enjoy permanently free endpoints for Qwen, DeepSeek V3, and GLM-4',
    logo_url: 'https://siliconflow.cn/favicon.ico',
    description: 'High-performance Asian AI infrastructure providing free endpoints for DeepSeek V3/R1, Qwen 2.5 72B, and GLM open-source weights.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'for-the-zero/Free-LLM-Collection',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-sf-1',
        provider_id: 'prov-siliconflow',
        model_api_id: 'deepseek-ai/DeepSeek-V3',
        name: 'DeepSeek V3 (SiliconFlow Free)',
        context_window: 64000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.siliconflow.cn/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-sf-2',
        provider_id: 'prov-siliconflow',
        model_api_id: 'Qwen/Qwen2.5-72B-Instruct',
        name: 'Qwen 2.5 72B Instruct (SiliconFlow)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.siliconflow.cn/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cloudflare-workers',
    name: 'Cloudflare Workers AI',
    slug: 'cloudflare-workers',
    website: 'https://workers.cloudflare.com',
    signup_url: 'https://dash.cloudflare.com',
    api_key_guide: '1. Create a Cloudflare account\n2. Enable Workers AI in dashboard\n3. Get API token with Workers AI permission\n4. 10,000 free Neurons daily limit',
    logo_url: 'https://www.cloudflare.com/favicon.ico',
    description: 'Serverless GPU edge computing platform delivering 10,000 free daily Neurons for Llama 3.3, DeepSeek R1 Distill, and Whisper models.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'abbosaliboev/free-ai-bible',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cf-1',
        provider_id: 'prov-cloudflare-workers',
        model_api_id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
        name: 'Llama 3.3 70B Instruct (Cloudflare Edge)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://developers.cloudflare.com/workers-ai/models/',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 10000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-cf-2',
        provider_id: 'prov-cloudflare-workers',
        model_api_id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b',
        name: 'DeepSeek R1 Distill 32B (Cloudflare Edge)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://developers.cloudflare.com/workers-ai/models/',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 10000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-mistral',
    name: 'Mistral AI (La Plateforme)',
    slug: 'mistral',
    website: 'https://mistral.ai',
    signup_url: 'https://console.mistral.ai',
    api_key_guide: '1. Register at console.mistral.ai\n2. Navigate to API Keys section\n3. Start using the free Experimentation Tier with 1 req/sec limit on open Mistral models',
    logo_url: 'https://mistral.ai/favicon.ico',
    description: 'European AI champion offering free developer tier access to open-weights models like Mistral Small, Codestral, and Pixtral.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'mistralai/mistral-common',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-mistral-1',
        provider_id: 'prov-mistral',
        model_api_id: 'mistral-small-latest',
        name: 'Mistral Small (Free Experimentation)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://mistral.ai/technology/#models',
        rate_limit_per_minute: 60,
        rate_limit_per_day: 5000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-mistral-2',
        provider_id: 'prov-mistral',
        model_api_id: 'pixtral-12b-2409',
        name: 'Pixtral 12B Vision (Mistral Free Tier)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://mistral.ai/news/pixtral-12b/',
        rate_limit_per_minute: 60,
        rate_limit_per_day: 5000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cohere',
    name: 'Cohere',
    slug: 'cohere',
    website: 'https://cohere.com',
    signup_url: 'https://dashboard.cohere.com/api-keys',
    api_key_guide: '1. Sign up on dashboard.cohere.com\n2. Get your free Trial API Key\n3. Enjoy 1,000 free API calls/month for Command R and Embed models',
    logo_url: 'https://cohere.com/favicon.ico',
    description: 'Enterprise NLP powerhouse offering free developer trial keys with generous rate limits for Command R, Command R+, and multilingual embeddings.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'cohere-ai/cohere-python',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cohere-1',
        provider_id: 'prov-cohere',
        model_api_id: 'command-r-08-2024',
        name: 'Command R (Free Trial Key)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cohere.com/models/command-r',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  }
];
