import type { ProviderWithModels, FlatModel } from './types';
import { formatModelDisplayName } from './utils';

const STATIC_TIMESTAMP = '2026-08-13T10:00:00.000Z';

const RAW_INITIAL_PROVIDERS: ProviderWithModels[] = [
  {
    id: 'prov-groq',
    name: 'Groq',
    slug: 'groq',
    website: 'https://groq.com',
    signup_url: 'https://console.groq.com',
    api_key_guide: '1. Sign up at console.groq.com\n2. Navigate to API Keys section\n3. Click "Create API Key"\n4. Set GROQ_API_KEY env variable',
    logo_url: 'https://groq.com/wp-content/uploads/2024/03/Groq_Logo_Primary_RGB_Red.png',
    description: 'Ultra-fast LPU inference engine powering open-weights models like Llama 3.3, DeepSeek R1, Gemma 2, and Whisper at multi-hundred tokens/sec.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'groq/groq-sdk-python',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-groq-1',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B Versatile',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-2',
        provider_id: 'prov-groq',
        model_api_id: 'deepseek-r1-distill-llama-70b',
        name: 'DeepSeek R1 Distill Llama 70B',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-3',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-4',
        provider_id: 'prov-groq',
        model_api_id: 'gemma2-9b-it',
        name: 'Gemma 2 9B Instruction',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 88,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-5',
        provider_id: 'prov-groq',
        model_api_id: 'mixtral-8x7b-32768',
        name: 'Mixtral 8x7B Instruct',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-6',
        provider_id: 'prov-groq',
        model_api_id: 'llama-guard-3-8b',
        name: 'Llama Guard 3 8B (Safety Filter)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Safety Guardrail',
        popularity_score: 82,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-7',
        provider_id: 'prov-groq',
        model_api_id: 'whisper-large-v3',
        name: 'Whisper Large v3 (Speech-to-Text)',
        context_window: 1500,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-8',
        provider_id: 'prov-groq',
        model_api_id: 'whisper-large-v3-turbo',
        name: 'Whisper Large v3 Turbo',
        context_window: 1500,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-9',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.2-11b-vision-preview',
        name: 'Llama 3.2 11B Vision Preview',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 7000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-10',
        provider_id: 'prov-groq',
        model_api_id: 'llama-3.2-90b-vision-preview',
        name: 'Llama 3.2 90B Vision Preview',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 3500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-11',
        provider_id: 'prov-groq',
        model_api_id: 'deepseek-r1-distill-qwen-32b',
        name: 'DeepSeek R1 Distill Qwen 32B',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-groq-12',
        provider_id: 'prov-groq',
        model_api_id: 'qwen-2.5-coder-32b',
        name: 'Qwen 2.5 Coder 32B (Groq LPU)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://console.groq.com/docs/models',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-orcarouter',
    name: 'OrcaRouter',
    slug: 'orcarouter',
    website: 'https://www.orcarouter.ai',
    signup_url: 'https://www.orcarouter.ai/console/token',
    api_key_guide: '1. Visit https://www.orcarouter.ai/ and register/login to your account.\n2. Navigate to Console Token at https://www.orcarouter.ai/console/token\n3. Generate your Free API Key.\n4. Call router endpoints with verified free models such as deepseek/deepseek-v4-flash-free, deepseek/deepseek-v4-pro-free, and qwen/qwen3.8-27b-free.',
    logo_url: 'https://www.orcarouter.ai/favicon.ico',
    description: 'High-speed unified AI model routing & aggregation gateway providing ultra-low latency inference, high-availability failover, and generous free tiers for top-tier open models like DeepSeek V4 Flash, DeepSeek V4 Pro, and Qwen 3.8.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'orcarouter/orcarouter-sdk',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-orca-1',
        provider_id: 'prov-orcarouter',
        model_api_id: 'deepseek/deepseek-v4-flash-free',
        name: 'DeepSeek-V4-Flash-Free',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://www.orcarouter.ai/models/deepseek/deepseek-v4-flash-free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-orca-2',
        provider_id: 'prov-orcarouter',
        model_api_id: 'deepseek/deepseek-v4-pro-free',
        name: 'DeepSeek-V4-Pro-Free',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://www.orcarouter.ai/models/deepseek/deepseek-v4-pro-free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-orca-3',
        provider_id: 'prov-orcarouter',
        model_api_id: 'qwen/qwen3.8-27b-free',
        name: 'Qwen3.8-27B-Free',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://www.orcarouter.ai/models/qwen/qwen3.8-27b-free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-xkiro',
    name: 'xKiro',
    slug: 'xkiro',
    website: 'https://xkiro.com',
    signup_url: 'https://xkiro.com/dashboard/api/keys',
    api_key_guide: '1. Visit https://xkiro.com/ and create your account.\n2. Go to Dashboard > API Keys at https://xkiro.com/dashboard/api/keys\n3. Click "Create Key" to get your free API key.\n4. Browse and filter all free models at https://xkiro.com/dashboard/models?sort=recommended&price=free',
    logo_url: 'https://xkiro.com/favicon.ico',
    description: 'High-performance distributed AI inference cloud offering free access to DeepSeek V4, Mistral, Qwen3, MiniMax, and MiMO models with OpenAI-compatible API.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'xkiro-ai/xkiro-python',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-xkiro-1',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/mistral-large-2512',
        name: 'Mistral-Large-2512',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-2',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/mistral-medium-3.5',
        name: 'Mistral-Medium-3.5',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-3',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/mistral-small-2603',
        name: 'Mistral-Small-2603',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-4',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/codestral-2508',
        name: 'Codestral-2508',
        context_window: 262144,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-5',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/devstral-medium',
        name: 'Devstral-Medium',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-6',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/ministral-14b',
        name: 'Ministral-14B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-7',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/ministral-8b',
        name: 'Ministral-8B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-8',
        provider_id: 'prov-xkiro',
        model_api_id: 'mistralai/ministral-3b',
        name: 'Ministral-3B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-9',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.7',
        name: 'MiniMax-M2.7',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-10',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.7-highspeed',
        name: 'MiniMax-M2.7-HighSpeed',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-11',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.5',
        name: 'MiniMax-M2.5',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-12',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.5-highspeed',
        name: 'MiniMax-M2.5-HighSpeed',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-13',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.1',
        name: 'MiniMax-M2.1',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-14',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2.1-highspeed',
        name: 'MiniMax-M2.1-HighSpeed',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-15',
        provider_id: 'prov-xkiro',
        model_api_id: 'minimax/minimax-m2',
        name: 'MiniMax-M2',
        context_window: 200000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 89,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-16',
        provider_id: 'prov-xkiro',
        model_api_id: 'xiaomi/mimo-v2.5-pro',
        name: 'MiMO-v2.5-Pro',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-17',
        provider_id: 'prov-xkiro',
        model_api_id: 'xiaomi/mimo-v2.5',
        name: 'MiMO-v2.5',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-18',
        provider_id: 'prov-xkiro',
        model_api_id: 'deepseek/deepseek-v4-pro',
        name: 'DeepSeek-V4-Pro',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-19',
        provider_id: 'prov-xkiro',
        model_api_id: 'deepseek/deepseek-v4-flash',
        name: 'DeepSeek-V4-Flash',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-20',
        provider_id: 'prov-xkiro',
        model_api_id: 'deepseek/deepseek-v3.2',
        name: 'DeepSeek-V3.2',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-21',
        provider_id: 'prov-xkiro',
        model_api_id: 'deepseek/deepseek-chat-v3.1',
        name: 'DeepSeek-Chat-V3.1',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-22',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.8-max',
        name: 'Qwen3.8-Max',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-23',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.7-max',
        name: 'Qwen3.7-Max',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-24',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.7-plus',
        name: 'Qwen3.7-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-25',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.6-max-preview',
        name: 'Qwen3.6-Max-Preview',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-26',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.6-plus',
        name: 'Qwen3.6-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-27',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.6-27b',
        name: 'Qwen3.6-27B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-28',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.6-35b-a3b',
        name: 'Qwen3.6-35B-A3B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-29',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.5-plus',
        name: 'Qwen3.5-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-30',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.5-397b-a17b',
        name: 'Qwen3.5-397B-A17B',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-31',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.5-omni-plus',
        name: 'Qwen3.5-Omni-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-32',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.5-flash',
        name: 'Qwen3.5-Flash',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-33',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3.5-omni-flash',
        name: 'Qwen3.5-Omni-Flash',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-34',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3-coder-plus',
        name: 'Qwen3-Coder-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-35',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3-max',
        name: 'Qwen3-Max',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-36',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3-vl-plus',
        name: 'Qwen3-VL-Plus',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-37',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen3-omni-flash',
        name: 'Qwen3-Omni-Flash',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-xkiro-38',
        provider_id: 'prov-xkiro',
        model_api_id: 'qwen/qwen-plus-2025-07-28',
        name: 'Qwen-Plus-2025-07-28',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://xkiro.com/dashboard/models?sort=recommended&price=free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-openrouter',
    name: 'OpenRouter',
    slug: 'openrouter',
    website: 'https://openrouter.ai',
    signup_url: 'https://openrouter.ai/keys',
    api_key_guide: '1. Register on openrouter.ai\n2. Go to Keys tab and click Create Key\n3. Filter models with :free tag',
    logo_url: 'https://openrouter.ai/favicon.ico',
    description: 'Unified AI gateway hosting over 20+ completely free LLM models alongside paid endpoints with zero minimum commitment.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'alexrudy/openrouter',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-or-1',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemini-2.0-flash-exp:free',
        name: 'Gemini 2.0 Flash Experimental (Free)',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemini-2.0-flash-exp:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 200,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-2',
        provider_id: 'prov-openrouter',
        model_api_id: 'deepseek/deepseek-r1:free',
        name: 'DeepSeek R1 (Free OpenRouter)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/deepseek/deepseek-r1:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-3',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.3-70b-instruct:free',
        name: 'Llama 3.3 70B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.3-70b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-4',
        provider_id: 'prov-openrouter',
        model_api_id: 'qwen/qwen-2.5-72b-instruct:free',
        name: 'Qwen 2.5 72B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/qwen/qwen-2.5-72b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-5',
        provider_id: 'prov-openrouter',
        model_api_id: 'mistralai/mistral-7b-instruct:free',
        name: 'Mistral 7B Instruct v0.3 (Free)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/mistralai/mistral-7b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 89,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-6',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemma-2-9b-it:free',
        name: 'Gemma 2 9B Instruct (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemma-2-9b-it:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 87,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-7',
        provider_id: 'prov-openrouter',
        model_api_id: 'nousresearch/hermes-3-llama-3.1-405b:free',
        name: 'Hermes 3 Llama 3.1 405B (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/nousresearch/hermes-3-llama-3.1-405b:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 200,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-8',
        provider_id: 'prov-openrouter',
        model_api_id: 'sophosympatheia/rogue-rose-103b-v0.2:free',
        name: 'Rogue Rose 103B v0.2 (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/sophosympatheia/rogue-rose-103b-v0.2:free',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 200,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 80,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-9',
        provider_id: 'prov-openrouter',
        model_api_id: 'huggingfaceh4/zephyr-7b-beta:free',
        name: 'Zephyr 7B Beta (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/huggingfaceh4/zephyr-7b-beta:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 83,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-10',
        provider_id: 'prov-openrouter',
        model_api_id: 'openchat/openchat-7b:free',
        name: 'OpenChat 3.5 7B (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/openchat/openchat-7b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 81,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-11',
        provider_id: 'prov-openrouter',
        model_api_id: 'gryphe/mythomax-l2-13b:free',
        name: 'MythoMax L2 13B (Free)',
        context_window: 4096,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/gryphe/mythomax-l2-13b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 84,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-12',
        provider_id: 'prov-openrouter',
        model_api_id: 'liquid/lfm-40b:free',
        name: 'Liquid LFM 40B MoE (Free)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/liquid/lfm-40b:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 88,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-13',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.2-11b-vision-instruct:free',
        name: 'Llama 3.2 11B Vision Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.2-11b-vision-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-14',
        provider_id: 'prov-openrouter',
        model_api_id: 'nvidia/llama-3.1-nemotron-70b-instruct:free',
        name: 'NVIDIA Llama 3.1 Nemotron 70B (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/nvidia/llama-3.1-nemotron-70b-instruct:free',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 400,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-15',
        provider_id: 'prov-openrouter',
        model_api_id: 'qwen/qwen-2.5-coder-32b-instruct:free',
        name: 'Qwen 2.5 Coder 32B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/qwen/qwen-2.5-coder-32b-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-16',
        provider_id: 'prov-openrouter',
        model_api_id: 'meta-llama/llama-3.1-8b-instruct:free',
        name: 'Llama 3.1 8B Instruct (Free)',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/meta-llama/llama-3.1-8b-instruct:free',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-17',
        provider_id: 'prov-openrouter',
        model_api_id: 'microsoft/phi-3-medium-128k-instruct:free',
        name: 'Phi-3 Medium 128k Instruct (Free)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/microsoft/phi-3-medium-128k-instruct:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 800,
        multimodal: false,
        category: 'Fast / Small',
        popularity_score: 86,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-18',
        provider_id: 'prov-openrouter',
        model_api_id: 'google/gemma-2-27b-it:free',
        name: 'Gemma 2 27B Instruct (Free)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/google/gemma-2-27b-it:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 89,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-or-19',
        provider_id: 'prov-openrouter',
        model_api_id: 'deepseek/deepseek-chat:free',
        name: 'DeepSeek V3 Chat (Free)',
        context_window: 64000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://openrouter.ai/deepseek/deepseek-chat:free',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-google-aistudio',
    name: 'Google AI Studio',
    slug: 'google-aistudio',
    website: 'https://aistudio.google.com',
    signup_url: 'https://aistudio.google.com/app/apikey',
    api_key_guide: '1. Visit Google AI Studio\n2. Click "Get API key"\n3. Generate key in Google Cloud project\n4. Generous free tier quotas reset daily',
    logo_url: 'https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a611345.svg',
    description: 'Official developer interface for Gemini models featuring 1 million+ token context window, audio/video input, and high speed.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'google-gemini/generative-ai-js',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-goog-37-flash',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.7-flash',
        name: 'Gemini 3.7 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini#gemini-3.7-flash',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-37-thinking',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.7-flash-thinking',
        name: 'Gemini 3.7 Flash Thinking',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Reasoning',
        popularity_score: 100,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-31-lite',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-3.1-flash-lite',
        name: 'Gemini 3.1 Flash Lite',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-1',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-2',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-2.0-flash-lite',
        name: 'Gemini 2.0 Flash Lite',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-3',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        context_window: 2097152,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 2,
        rate_limit_per_day: 50,
        multimodal: true,
        category: 'Large Context',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-4',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        context_window: 1048576,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/pricing',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-goog-gemma2-27b',
        provider_id: 'prov-google-aistudio',
        model_api_id: 'gemma-2-27b-it',
        name: 'Gemma 2 27B IT',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://ai.google.dev/gemma',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cerebras',
    name: 'Cerebras AI',
    slug: 'cerebras',
    website: 'https://cerebras.ai',
    signup_url: 'https://cloud.cerebras.ai',
    api_key_guide: '1. Sign up at cloud.cerebras.ai\n2. Get API key from dashboard\n3. Enjoy lightning-fast 2,000+ tokens/sec output rate.',
    logo_url: 'https://cerebras.ai/wp-content/uploads/2023/11/logo.svg',
    description: 'Wafer-Scale Engine wafer-chip hardware delivering unmatched generation speeds up to 2,000 tokens per second for Llama 3 models.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'cerebras/cerebras-cloud-sdk',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cer-1',
        provider_id: 'prov-cerebras',
        model_api_id: 'llama3.3-70b',
        name: 'Llama 3.3 70B (Wafer Speed)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.cerebras.ai',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Extreme Speed',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-cer-2',
        provider_id: 'prov-cerebras',
        model_api_id: 'llama3.1-8b',
        name: 'Llama 3.1 8B (Wafer Speed)',
        context_window: 8192,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.cerebras.ai',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 14400,
        multimodal: false,
        category: 'Extreme Speed',
        popularity_score: 90,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-sambanova',
    name: 'SambaNova Systems',
    slug: 'sambanova',
    website: 'https://sambanova.ai',
    signup_url: 'https://cloud.sambanova.ai',
    api_key_guide: '1. Register at cloud.sambanova.ai\n2. Generate API key\n3. Full free access to DeepSeek R1 671B and Llama 3.3 70B.',
    logo_url: 'https://sambanova.ai/hubfs/SambaNova_Logo_Primary_RGB.svg',
    description: 'SN40L Reconfigurable Dataflow Unit architecture serving full-size 671B parameter DeepSeek R1 and Llama 3.3 70B at ultra speed.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'sambanova/sambanova-suite',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-samba-1',
        provider_id: 'prov-sambanova',
        model_api_id: 'DeepSeek-R1',
        name: 'DeepSeek R1 (Full 671B)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.sambanova.ai',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-samba-2',
        provider_id: 'prov-sambanova',
        model_api_id: 'Meta-Llama-3.3-70B-Instruct',
        name: 'Meta Llama 3.3 70B Instruct',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.sambanova.ai',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 91,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-huggingface',
    name: 'Hugging Face Inference API',
    slug: 'huggingface',
    website: 'https://huggingface.co',
    signup_url: 'https://huggingface.co/settings/tokens',
    api_key_guide: '1. Sign up on Hugging Face\n2. Navigate to Settings > Access Tokens\n3. Create a read token\n4. Call router.huggingface.co endpoints',
    logo_url: 'https://huggingface.co/front/assets/huggingface_logo-noborder.svg',
    description: 'Serverless inference endpoint hosting thousands of open-source fine-tuned models and community releases for free.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'huggingface/huggingface_hub',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-hf-1',
        provider_id: 'prov-huggingface',
        model_api_id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
        name: 'Qwen 2.5 Coder 32B Instruct',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Code / Math',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-hf-2',
        provider_id: 'prov-huggingface',
        model_api_id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
        name: 'DeepSeek R1 Distill Qwen 32B (Serverless)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
        rate_limit_per_minute: 10,
        rate_limit_per_day: 500,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-github-models',
    name: 'GitHub Models',
    slug: 'github-models',
    website: 'https://github.com/marketplace/models',
    signup_url: 'https://github.com/marketplace/models',
    api_key_guide: '1. Go to github.com/marketplace/models\n2. Log in with your GitHub account\n3. Generate a GitHub Personal Access Token (PAT)\n4. Enjoy free access to OpenAI GPT-4o, Llama 3.3, and Mistral Large!',
    logo_url: 'https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png',
    description: 'GitHub official free AI inference playground giving developers direct OpenAI, Llama 3.3, and Azure AI model access with a standard GitHub Personal Access Token.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'open-free-llm-api/awesome-freellm-apis',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-ghm-1',
        provider_id: 'prov-github-models',
        model_api_id: 'gpt-4o',
        name: 'GPT-4o (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-openai/gpt-4o',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 99,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-2',
        provider_id: 'prov-github-models',
        model_api_id: 'gpt-4o-mini',
        name: 'GPT-4o Mini (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-openai/gpt-4o-mini',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1500,
        multimodal: true,
        category: 'Fast / Small',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-3',
        provider_id: 'prov-github-models',
        model_api_id: 'Meta-Llama-3.3-70B-Instruct',
        name: 'Llama 3.3 70B Instruct (GitHub)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-meta/Meta-Llama-3-3-70B-Instruct',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-ghm-4',
        provider_id: 'prov-github-models',
        model_api_id: 'Mistral-large-2411',
        name: 'Mistral Large 2 (GitHub Playground)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://github.com/marketplace/models/azure-mistral/Mistral-large-2411',
        rate_limit_per_minute: 15,
        rate_limit_per_day: 150,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-nvidia-nim',
    name: 'NVIDIA Build NIMs',
    slug: 'nvidia-nim',
    website: 'https://build.nvidia.com',
    signup_url: 'https://build.nvidia.com',
    api_key_guide: '1. Sign in to build.nvidia.com with NVIDIA account\n2. Receive 1,000 free API credits\n3. Access accelerated NIM endpoints for Llama 3.3 70B & DeepSeek R1',
    logo_url: 'https://www.nvidia.com/favicon.ico',
    description: 'NVIDIA official cloud microservices platform hosting optimized inference containers for DeepSeek R1, Llama 3.3 70B, and Nemotron with free API testing credits.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'MrFadiAi/free-llm-gateway',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-nv-1',
        provider_id: 'prov-nvidia-nim',
        model_api_id: 'deepseek-ai/deepseek-r1',
        name: 'DeepSeek R1 (NVIDIA NIM)',
        context_window: 16384,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://build.nvidia.com/deepseek-ai/deepseek-r1',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 98,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-nv-2',
        provider_id: 'prov-nvidia-nim',
        model_api_id: 'nvidia/llama-3.1-nemotron-70b-instruct',
        name: 'NVIDIA Llama 3.1 Nemotron 70B NIM',
        context_window: 131072,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-siliconflow',
    name: 'SiliconFlow (SiliconCloud)',
    slug: 'siliconflow',
    website: 'https://siliconflow.cn',
    signup_url: 'https://cloud.siliconflow.cn',
    api_key_guide: '1. Register at cloud.siliconflow.cn\n2. Navigate to API Keys section\n3. Enjoy permanently free endpoints for Qwen, DeepSeek V3, and GLM-4',
    logo_url: 'https://siliconflow.cn/favicon.ico',
    description: 'High-performance Asian AI infrastructure providing free endpoints for DeepSeek V3/R1, Qwen 2.5 72B, and GLM open-source weights.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'for-the-zero/Free-LLM-Collection',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-sf-1',
        provider_id: 'prov-siliconflow',
        model_api_id: 'deepseek-ai/DeepSeek-V3',
        name: 'DeepSeek V3 (SiliconFlow Free)',
        context_window: 64000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.siliconflow.cn/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 97,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-sf-2',
        provider_id: 'prov-siliconflow',
        model_api_id: 'Qwen/Qwen2.5-72B-Instruct',
        name: 'Qwen 2.5 72B Instruct (SiliconFlow)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cloud.siliconflow.cn/models',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 2000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cloudflare-workers',
    name: 'Cloudflare Workers AI',
    slug: 'cloudflare-workers',
    website: 'https://workers.cloudflare.com',
    signup_url: 'https://dash.cloudflare.com',
    api_key_guide: '1. Create a Cloudflare account\n2. Enable Workers AI in dashboard\n3. Get API token with Workers AI permission\n4. 10,000 free Neurons daily limit',
    logo_url: 'https://www.cloudflare.com/favicon.ico',
    description: 'Serverless GPU edge computing platform delivering 10,000 free daily Neurons for Llama 3.3, DeepSeek R1 Distill, and Whisper models.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'abbosaliboev/free-ai-bible',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cf-1',
        provider_id: 'prov-cloudflare-workers',
        model_api_id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
        name: 'Llama 3.3 70B Instruct (Cloudflare Edge)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://developers.cloudflare.com/workers-ai/models/',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 10000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 95,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-cf-2',
        provider_id: 'prov-cloudflare-workers',
        model_api_id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b',
        name: 'DeepSeek R1 Distill 32B (Cloudflare Edge)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://developers.cloudflare.com/workers-ai/models/',
        rate_limit_per_minute: 30,
        rate_limit_per_day: 10000,
        multimodal: false,
        category: 'Reasoning',
        popularity_score: 96,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-mistral',
    name: 'Mistral AI (La Plateforme)',
    slug: 'mistral',
    website: 'https://mistral.ai',
    signup_url: 'https://console.mistral.ai',
    api_key_guide: '1. Register at console.mistral.ai\n2. Navigate to API Keys section\n3. Start using the free Experimentation Tier with 1 req/sec limit on open Mistral models',
    logo_url: 'https://mistral.ai/favicon.ico',
    description: 'European AI champion offering free developer tier access to open-weights models like Mistral Small, Codestral, and Pixtral.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'mistralai/mistral-common',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-mistral-1',
        provider_id: 'prov-mistral',
        model_api_id: 'mistral-small-latest',
        name: 'Mistral Small (Free Experimentation)',
        context_window: 32768,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://mistral.ai/technology/#models',
        rate_limit_per_minute: 60,
        rate_limit_per_day: 5000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 92,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      },
      {
        id: 'mod-mistral-2',
        provider_id: 'prov-mistral',
        model_api_id: 'pixtral-12b-2409',
        name: 'Pixtral 12B Vision (Mistral Free Tier)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://mistral.ai/news/pixtral-12b/',
        rate_limit_per_minute: 60,
        rate_limit_per_day: 5000,
        multimodal: true,
        category: 'Multimodal',
        popularity_score: 94,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  },
  {
    id: 'prov-cohere',
    name: 'Cohere',
    slug: 'cohere',
    website: 'https://cohere.com',
    signup_url: 'https://dashboard.cohere.com/api-keys',
    api_key_guide: '1. Sign up on dashboard.cohere.com\n2. Get your free Trial API Key\n3. Enjoy 1,000 free API calls/month for Command R and Embed models',
    logo_url: 'https://cohere.com/favicon.ico',
    description: 'Enterprise NLP powerhouse offering free developer trial keys with generous rate limits for Command R, Command R+, and multilingual embeddings.',
    is_free: true,
    discovered_via: 'tier1-api',
    source_repo: 'cohere-ai/cohere-python',
    status: 'active',
    last_checked_at: STATIC_TIMESTAMP,
    verified_at: STATIC_TIMESTAMP,
    created_at: STATIC_TIMESTAMP,
    updated_at: STATIC_TIMESTAMP,
    models: [
      {
        id: 'mod-cohere-1',
        provider_id: 'prov-cohere',
        model_api_id: 'command-r-08-2024',
        name: 'Command R (Free Trial Key)',
        context_window: 128000,
        is_free: true,
        price_input_per_mtok: 0,
        price_output_per_mtok: 0,
        external_url: 'https://cohere.com/models/command-r',
        rate_limit_per_minute: 20,
        rate_limit_per_day: 1000,
        multimodal: false,
        category: 'General LLM',
        popularity_score: 93,
        discovered_via: 'tier1-api',
        status: 'active',
        last_checked_at: STATIC_TIMESTAMP,
        verified_at: STATIC_TIMESTAMP,
        created_at: STATIC_TIMESTAMP,
        updated_at: STATIC_TIMESTAMP
      }
    ]
  }
];

export const INITIAL_PROVIDERS: ProviderWithModels[] = RAW_INITIAL_PROVIDERS.map((p) => ({
  ...p,
  models: (p.models || []).map((m) => ({
    ...m,
    name: formatModelDisplayName(m.name || m.model_api_id),
  })),
}));
